version: "3.9"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  fastapi:
    build: .
    container_name: message_dispatcher_api
    ports:
      - "8000:8000"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
